name: CI-CD

on:
  push:
    branches: [ principal ]
  pull_request:
    branches: [ principal ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Run tests
        run: echo "CI funcionando com sucesso"

      - name: Deploy
        run: echo "CD funcionando com sucesso"
